# Generated by Django 4.1 on 2022-08-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=50, null=True)),
                ('classname', models.CharField(max_length=50, null=True)),
                ('credit', models.IntegerField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='graduate',
            name='deepmajor',
            field=models.IntegerField(null=True),
        ),
    ]
