# Generated by Django 4.1 on 2022-08-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guest',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='classkind',
            field=models.TextField(max_length=10, null=True),
        ),
    ]
